spring.application.name=userfeedback-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/db_userfeedback}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:userfeedback_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:UserFeedback123!}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true